#!/bin/sh
set -e

mkdir -p build-xcode
cd build-xcode
cmake -DLLVM_TARGETS_TO_BUILD:STRING="X86" -DLLVM_BUILD_TOOLS:BOOL=OFF -DCMAKE_INSTALL_PREFIX:PATH="$HOME/.local" -DCMAKE_OSX_DEPLOYMENT_TARGET=10.8 -G "Xcode" ../
