#!/bin/sh

# build and install vpx in toplevel directory
pushd ../../
./configure --prefix="$HOME/.local"
make
make install
popd

# install cmake files
cmake -DCMAKE_INSTALL_PREFIX:PATH="$HOME/.local" -P install.cmake
