ADD_LIBRARY(vpx STATIC IMPORTED)

# Compute the installation prefix relative to this file.
GET_FILENAME_COMPONENT(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
GET_FILENAME_COMPONENT(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
GET_FILENAME_COMPONENT(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)

# Debug
#SET_PROPERTY(TARGET vpx APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
#SET_TARGET_PROPERTIES(vpx PROPERTIES
#  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
#  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/lib/libvpx_g.a"
#)

# Release
SET_PROPERTY(TARGET vpx APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vpx PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/libvpx.a"
)
